# Generated by Django 5.2.2 on 2025-06-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutASTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='about/')),
                ('vision_statement', models.TextField()),
                ('history_summary', models.TextField()),
                ('campus_photo', models.ImageField(upload_to='about/')),
                ('established_year', models.PositiveIntegerField(default=2007)),
                ('student_count', models.PositiveIntegerField(default=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About ASTU',
                'verbose_name_plural': 'About ASTU',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cover_image', models.ImageField(upload_to='departments/')),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('intro_message', models.TextField()),
                ('theme_color', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyTribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='faculty/')),
                ('message', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lowest first)')),
            ],
            options={
                'verbose_name': 'Faculty Tribute',
                'verbose_name_plural': 'Faculty Tributes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PresidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='president/')),
                ('speech', models.TextField()),
                ('position', models.CharField(default='University President', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'President Message',
                'verbose_name_plural': 'President Messages',
            },
        ),
        migrations.CreateModel(
            name='AlumniHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='alumni/')),
                ('bio', models.TextField()),
                ('achievement', models.TextField()),
                ('graduation_year', models.PositiveIntegerField()),
                ('current_position', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='yearbook.department')),
            ],
            options={
                'verbose_name': 'Alumni Highlight',
                'verbose_name_plural': 'Alumni Highlights',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='MemoryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='memories/')),
                ('caption', models.TextField()),
                ('memory_type', models.CharField(choices=[('GRAD', 'Graduation'), ('PARTY', 'Party'), ('STUDY', 'Study Session'), ('SPORT', 'Sports Event'), ('OTHER', 'Other')], default='OTHER', help_text='Category for grouping memories', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='yearbook.department')),
            ],
            options={
                'verbose_name': 'Memory Board Entry',
                'verbose_name_plural': 'Memory Board Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='students/')),
                ('quote', models.CharField(max_length=200)),
                ('last_words', models.TextField()),
                ('highlight_tagline', models.CharField(max_length=100)),
                ('description', models.TextField(help_text="What I'll miss most, proudest moments, etc.")),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='yearbook.department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
