# Generated by Django 5.2.2 on 2025-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_insa_cyber_talent_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneralmessage',
            name='name',
            field=models.CharField(default='H.E. Tigist Hamid', max_length=100),
        ),
        migrations.AlterField(
            model_name='directorgeneralmessage',
            name='photo',
            field=models.ImageField(upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='directorgeneralmessage',
            name='position',
            field=models.CharField(default='Director General of Information Network Security Administration (INSA), Ethiopia', max_length=200),
        ),
        migrations.AlterField(
            model_name='traineesuccessstory',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='traineesuccessstory',
            name='photo',
            field=models.ImageField(upload_to='trainees/'),
        ),
    ]
