# Generated by Django 5.2.2 on 2025-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_alter_directorgeneralmessage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='STU001', help_text='Unique student ID for certificate generation', max_length=20, unique=True),
        ),
    ]
