# Generated by Django 5.2.2 on 2025-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0005_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Auto-generated ID (e.g., INSA009) - Leave blank for automatic generation', max_length=20, unique=True),
        ),
    ]
