# Generated by Django 5.2.2 on 2025-10-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Gaming & Entertainment)', max_length=100, unique=True)),
                ('icon', models.CharField(default='📷', help_text='Emoji or icon for the category (e.g., 🎮)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of this memory category')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for category (e.g., #3B82F6)', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory Category',
                'verbose_name_plural': 'Memory Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='memoryboard',
            name='memory_type',
            field=models.CharField(choices=[('GRAD', 'Graduation'), ('PARTY', 'Party'), ('STUDY', 'Study Session'), ('SPORT', 'Sports Event'), ('OTHER', 'Other')], default='OTHER', help_text="Legacy category field (deprecated, use 'category' instead)", max_length=10),
        ),
        migrations.AddField(
            model_name='memoryboard',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the category for this memory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='yearbook.memorycategory'),
        ),
    ]
