# Generated by Django 5.2.2 on 2025-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0007_memorycategory_alter_memoryboard_memory_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Leader's full name", max_length=150)),
                ('position', models.CharField(help_text='Official title/position', max_length=200)),
                ('photo', models.ImageField(help_text="Leader's professional photo", upload_to='leadership/')),
                ('message', models.TextField(help_text='Leadership message to the graduates')),
                ('leadership_type', models.CharField(choices=[('DIRECTOR', 'Director General'), ('CYBER_DIR', 'Cyber Talent Director'), ('DEP_DIR', 'Deputy Director'), ('ADVISOR', 'Senior Advisor'), ('OTHER', 'Other Leadership')], default='OTHER', help_text='Category of leadership position', max_length=15)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this leader on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Message',
                'verbose_name_plural': 'Leadership Messages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
